name: Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: "Build nginx"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - 
        name: Get source
        uses: actions/checkout@v2

      - 
        name: Get development tools
        run: sudo apt install golang cmake git gcc -y

      - 
        name: Get deps
        run: make clean && make dep

      - 
        name: Build
        run: make

  build-docker:
    name: "Build docker image"
    runs-on: ubuntu-latest
    steps:
      - 
        name: Get source
        uses: actions/checkout@v2

      # - 
      #   name: Setup QEMU
      #   uses: docker/setup-qemu-action@v1

      - 
        name: Setup Docker Buildx
        id: setup-buildx
        uses: docker/setup-buildx-action@v1

      - 
        name: Build docker image
        id: build-docker-image
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: "linux/amd64"

      - 
        name: Image digest
        run: echo ${{ steps.build-docker-image.digest }}
