name: Make All

on:
  push:
    branches: [ master ]

jobs:
  make-default:
    name: "Make Default"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./make_default
    steps:
      -
        name: mkdir
        run: mkdir -p make_default
        working-directory: .

      - 
        name: Get source
        uses: actions/checkout@v2

      - 
        name: Get development tools
        run: sudo apt install golang cmake git gcc -y

      - 
        name: Get deps
        run: make clean && make dep

      - 
        name: Build default
        run: make compile_process=4 build

      - 
        name: Build more
        run: make -f Makefile.more compile_process=4 build

      -
        name: Clean for building quic
        run: make clean && make -f Makefile.quic dep
        
      - 
        name: Build quic
        run: make -f Makefile.quic compile_process=4 build
